# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safras', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('produtos', models.ManyToManyField(to='produtos.Produto')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safras.Safra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
