# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
