# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoproduto',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servico',
            name='safra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='safras.Safra'),
        ),
        migrations.AlterField(
            model_name='servicoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_produto', to='produtos.Produto'),
        ),
        migrations.AlterField(
            model_name='servicoproduto',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_produto', to='servicos.Servico'),
        ),
    ]
