# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20161123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicoproduto',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
